sys:
  #数据库名
  database: challenger

#公共配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
        active: dev
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
      multipart:
          max-file-size: 20MB
          max-request-size: 20MB
          enabled: true
  #模板引擎配置
  freemarker:
      template-loader-path: classpath:/templates/
      prefer-file-system-access: false
      settings:
        template_update_delay: 0
        classic_compatible: true
        number_format: 0.######
        template_exception_handler: ignore
      request-context-attribute: rc
      charset: UTF-8
  #连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  #缓存配置
  cache:
      type: redis
      cache-names: ${sys.database}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  type-aliases-package: com.rancii.entity
  global-config:
    #刷新mapper 调试神器
    refresh: true
    #是否缓存 Sql 解析
    sql-parser-cache: true
    db-config:
      db-type: mysql
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #驼峰下划线转换
      column-underline: true
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #数据库大写下划线转换
      capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #    logic-delete-value: 1
    #    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #metaObjectHandler: com.rancii.config.SysMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
